# 1マスターノード、3ワーカーノード
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.19.0
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            "feature-gates": "EvenPodsSpread=true"
        scheduler:
          extraArgs:
            "feature-gates": "EvenPodsSpread=true"
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "region=asia-northeast1,zone=asia-northeast1-a,ingress-ready=true"
            authorization-mode: "AlwaysAllow"
  # ワーカーノードはマルチリージョンで稼働している想定でラベルを付与
  # Tokyo Regionに3ノードを配置
  - role: worker
    image: kindest/node:v1.19.0
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "region=asia-northeast1,zone=asia-northeast1-a"
  - role: worker
    image: kindest/node:v1.19.0
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "region=asia-northeast1,zone=asia-northeast1-b"
  - role: worker
    image: kindest/node:v1.19.0
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "region=asia-northeast1,zone=asia-northeast1-c"
