apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sample-replicaset
spec:
  # レプリカ数
  replicas: 5
  # 監視対象の条件
  selector:
    matchLabels:
      app: web
      env: sample
  # 対象のPodの情報
  template:
    metadata:
      name: nginx-srv
      labels:
        app: web
        env: sample
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.9-alpine
